// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: click.proto

// Specify package name to avoid name collision

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ユーザー情報を表すメッセージ型
type Click struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid      string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ContentId int64  `protobuf:"varint,3,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	UserId    int64  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Click) Reset() {
	*x = Click{}
	if protoimpl.UnsafeEnabled {
		mi := &file_click_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Click) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Click) ProtoMessage() {}

func (x *Click) ProtoReflect() protoreflect.Message {
	mi := &file_click_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Click.ProtoReflect.Descriptor instead.
func (*Click) Descriptor() ([]byte, []int) {
	return file_click_proto_rawDescGZIP(), []int{0}
}

func (x *Click) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Click) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Click) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *Click) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Click) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Click) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ClickList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Click []*Click `protobuf:"bytes,1,rep,name=click,proto3" json:"click,omitempty"`
}

func (x *ClickList) Reset() {
	*x = ClickList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_click_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickList) ProtoMessage() {}

func (x *ClickList) ProtoReflect() protoreflect.Message {
	mi := &file_click_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickList.ProtoReflect.Descriptor instead.
func (*ClickList) Descriptor() ([]byte, []int) {
	return file_click_proto_rawDescGZIP(), []int{1}
}

func (x *ClickList) GetClick() []*Click {
	if x != nil {
		return x.Click
	}
	return nil
}

// request
type ClickIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ClickIdRequest) Reset() {
	*x = ClickIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_click_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickIdRequest) ProtoMessage() {}

func (x *ClickIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_click_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickIdRequest.ProtoReflect.Descriptor instead.
func (*ClickIdRequest) Descriptor() ([]byte, []int) {
	return file_click_proto_rawDescGZIP(), []int{2}
}

func (x *ClickIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ClickIdListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []int64 `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
}

func (x *ClickIdListRequest) Reset() {
	*x = ClickIdListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_click_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickIdListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickIdListRequest) ProtoMessage() {}

func (x *ClickIdListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_click_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickIdListRequest.ProtoReflect.Descriptor instead.
func (*ClickIdListRequest) Descriptor() ([]byte, []int) {
	return file_click_proto_rawDescGZIP(), []int{3}
}

func (x *ClickIdListRequest) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

type ClickUserIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ClickUserIdRequest) Reset() {
	*x = ClickUserIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_click_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickUserIdRequest) ProtoMessage() {}

func (x *ClickUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_click_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickUserIdRequest.ProtoReflect.Descriptor instead.
func (*ClickUserIdRequest) Descriptor() ([]byte, []int) {
	return file_click_proto_rawDescGZIP(), []int{4}
}

func (x *ClickUserIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ClickContentIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentId int64 `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
}

func (x *ClickContentIdRequest) Reset() {
	*x = ClickContentIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_click_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickContentIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickContentIdRequest) ProtoMessage() {}

func (x *ClickContentIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_click_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickContentIdRequest.ProtoReflect.Descriptor instead.
func (*ClickContentIdRequest) Descriptor() ([]byte, []int) {
	return file_click_proto_rawDescGZIP(), []int{5}
}

func (x *ClickContentIdRequest) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

// response
type ClickBoolResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error bool `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ClickBoolResponse) Reset() {
	*x = ClickBoolResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_click_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickBoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickBoolResponse) ProtoMessage() {}

func (x *ClickBoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_click_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickBoolResponse.ProtoReflect.Descriptor instead.
func (*ClickBoolResponse) Descriptor() ([]byte, []int) {
	return file_click_proto_rawDescGZIP(), []int{6}
}

func (x *ClickBoolResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

var File_click_proto protoreflect.FileDescriptor

var file_click_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63,
	0x6c, 0x69, 0x63, 0x6b, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xa1, 0x01, 0x0a, 0x05, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x2f, 0x0a, 0x09, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x52,
	0x05, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x22, 0x20, 0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x24, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x63,
	0x6b, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d,
	0x0a, 0x12, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x36, 0x0a,
	0x15, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x42, 0x6f,
	0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x32, 0xd7, 0x03, 0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x26, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x2e, 0x63, 0x6c,
	0x69, 0x63, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x1a, 0x0c, 0x2e, 0x63, 0x6c, 0x69, 0x63,
	0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x06, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x0c, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x63,
	0x6b, 0x1a, 0x18, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x42,
	0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a,
	0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e,
	0x43, 0x6c, 0x69, 0x63, 0x6b, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x42, 0x6f, 0x6f, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x15, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x43, 0x6c,
	0x69, 0x63, 0x6b, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x63,
	0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x19, 0x2e,
	0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b,
	0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x1c, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10,
	0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x00, 0x12, 0x40, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x43, 0x6c,
	0x69, 0x63, 0x6b, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x10, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x43,
	0x6c, 0x69, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2e,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_click_proto_rawDescOnce sync.Once
	file_click_proto_rawDescData = file_click_proto_rawDesc
)

func file_click_proto_rawDescGZIP() []byte {
	file_click_proto_rawDescOnce.Do(func() {
		file_click_proto_rawDescData = protoimpl.X.CompressGZIP(file_click_proto_rawDescData)
	})
	return file_click_proto_rawDescData
}

var file_click_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_click_proto_goTypes = []interface{}{
	(*Click)(nil),                 // 0: click.Click
	(*ClickList)(nil),             // 1: click.ClickList
	(*ClickIdRequest)(nil),        // 2: click.ClickIdRequest
	(*ClickIdListRequest)(nil),    // 3: click.ClickIdListRequest
	(*ClickUserIdRequest)(nil),    // 4: click.ClickUserIdRequest
	(*ClickContentIdRequest)(nil), // 5: click.ClickContentIdRequest
	(*ClickBoolResponse)(nil),     // 6: click.ClickBoolResponse
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_click_proto_depIdxs = []int32{
	0, // 0: click.ClickList.click:type_name -> click.Click
	0, // 1: click.ClickService.Create:input_type -> click.Click
	0, // 2: click.ClickService.Update:input_type -> click.Click
	2, // 3: click.ClickService.Delete:input_type -> click.ClickIdRequest
	2, // 4: click.ClickService.GetById:input_type -> click.ClickIdRequest
	4, // 5: click.ClickService.GetListByUser:input_type -> click.ClickUserIdRequest
	5, // 6: click.ClickService.GetListByContent:input_type -> click.ClickContentIdRequest
	3, // 7: click.ClickService.GetListByIdList:input_type -> click.ClickIdListRequest
	7, // 8: click.ClickService.GetAll:input_type -> google.protobuf.Empty
	0, // 9: click.ClickService.Create:output_type -> click.Click
	6, // 10: click.ClickService.Update:output_type -> click.ClickBoolResponse
	6, // 11: click.ClickService.Delete:output_type -> click.ClickBoolResponse
	0, // 12: click.ClickService.GetById:output_type -> click.Click
	1, // 13: click.ClickService.GetListByUser:output_type -> click.ClickList
	1, // 14: click.ClickService.GetListByContent:output_type -> click.ClickList
	1, // 15: click.ClickService.GetListByIdList:output_type -> click.ClickList
	1, // 16: click.ClickService.GetAll:output_type -> click.ClickList
	9, // [9:17] is the sub-list for method output_type
	1, // [1:9] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_click_proto_init() }
func file_click_proto_init() {
	if File_click_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_click_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Click); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_click_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_click_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_click_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickIdListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_click_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickUserIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_click_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickContentIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_click_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickBoolResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_click_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_click_proto_goTypes,
		DependencyIndexes: file_click_proto_depIdxs,
		MessageInfos:      file_click_proto_msgTypes,
	}.Build()
	File_click_proto = out.File
	file_click_proto_rawDesc = nil
	file_click_proto_goTypes = nil
	file_click_proto_depIdxs = nil
}
