/**
 * @fileoverview gRPC-Web generated client stub for share
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.21.6
// source: share.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';
import * as share_pb from './share_pb';


export class ShareServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreate = new grpcWeb.MethodDescriptor(
    '/share.ShareService/Create',
    grpcWeb.MethodType.UNARY,
    share_pb.Share,
    share_pb.Share,
    (request: share_pb.Share) => {
      return request.serializeBinary();
    },
    share_pb.Share.deserializeBinary
  );

  create(
    request: share_pb.Share,
    metadata: grpcWeb.Metadata | null): Promise<share_pb.Share>;

  create(
    request: share_pb.Share,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: share_pb.Share) => void): grpcWeb.ClientReadableStream<share_pb.Share>;

  create(
    request: share_pb.Share,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: share_pb.Share) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/share.ShareService/Create',
        request,
        metadata || {},
        this.methodDescriptorCreate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/share.ShareService/Create',
    request,
    metadata || {},
    this.methodDescriptorCreate);
  }

  methodDescriptorUpdate = new grpcWeb.MethodDescriptor(
    '/share.ShareService/Update',
    grpcWeb.MethodType.UNARY,
    share_pb.Share,
    share_pb.ShareBoolResponse,
    (request: share_pb.Share) => {
      return request.serializeBinary();
    },
    share_pb.ShareBoolResponse.deserializeBinary
  );

  update(
    request: share_pb.Share,
    metadata: grpcWeb.Metadata | null): Promise<share_pb.ShareBoolResponse>;

  update(
    request: share_pb.Share,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: share_pb.ShareBoolResponse) => void): grpcWeb.ClientReadableStream<share_pb.ShareBoolResponse>;

  update(
    request: share_pb.Share,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: share_pb.ShareBoolResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/share.ShareService/Update',
        request,
        metadata || {},
        this.methodDescriptorUpdate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/share.ShareService/Update',
    request,
    metadata || {},
    this.methodDescriptorUpdate);
  }

  methodDescriptorDelete = new grpcWeb.MethodDescriptor(
    '/share.ShareService/Delete',
    grpcWeb.MethodType.UNARY,
    share_pb.ShareIdRequest,
    share_pb.ShareBoolResponse,
    (request: share_pb.ShareIdRequest) => {
      return request.serializeBinary();
    },
    share_pb.ShareBoolResponse.deserializeBinary
  );

  delete(
    request: share_pb.ShareIdRequest,
    metadata: grpcWeb.Metadata | null): Promise<share_pb.ShareBoolResponse>;

  delete(
    request: share_pb.ShareIdRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: share_pb.ShareBoolResponse) => void): grpcWeb.ClientReadableStream<share_pb.ShareBoolResponse>;

  delete(
    request: share_pb.ShareIdRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: share_pb.ShareBoolResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/share.ShareService/Delete',
        request,
        metadata || {},
        this.methodDescriptorDelete,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/share.ShareService/Delete',
    request,
    metadata || {},
    this.methodDescriptorDelete);
  }

  methodDescriptorGetById = new grpcWeb.MethodDescriptor(
    '/share.ShareService/GetById',
    grpcWeb.MethodType.UNARY,
    share_pb.ShareIdRequest,
    share_pb.Share,
    (request: share_pb.ShareIdRequest) => {
      return request.serializeBinary();
    },
    share_pb.Share.deserializeBinary
  );

  getById(
    request: share_pb.ShareIdRequest,
    metadata: grpcWeb.Metadata | null): Promise<share_pb.Share>;

  getById(
    request: share_pb.ShareIdRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: share_pb.Share) => void): grpcWeb.ClientReadableStream<share_pb.Share>;

  getById(
    request: share_pb.ShareIdRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: share_pb.Share) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/share.ShareService/GetById',
        request,
        metadata || {},
        this.methodDescriptorGetById,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/share.ShareService/GetById',
    request,
    metadata || {},
    this.methodDescriptorGetById);
  }

  methodDescriptorGetListByUser = new grpcWeb.MethodDescriptor(
    '/share.ShareService/GetListByUser',
    grpcWeb.MethodType.UNARY,
    share_pb.ShareUserIdRequest,
    share_pb.ShareList,
    (request: share_pb.ShareUserIdRequest) => {
      return request.serializeBinary();
    },
    share_pb.ShareList.deserializeBinary
  );

  getListByUser(
    request: share_pb.ShareUserIdRequest,
    metadata: grpcWeb.Metadata | null): Promise<share_pb.ShareList>;

  getListByUser(
    request: share_pb.ShareUserIdRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: share_pb.ShareList) => void): grpcWeb.ClientReadableStream<share_pb.ShareList>;

  getListByUser(
    request: share_pb.ShareUserIdRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: share_pb.ShareList) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/share.ShareService/GetListByUser',
        request,
        metadata || {},
        this.methodDescriptorGetListByUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/share.ShareService/GetListByUser',
    request,
    metadata || {},
    this.methodDescriptorGetListByUser);
  }

  methodDescriptorGetListByContent = new grpcWeb.MethodDescriptor(
    '/share.ShareService/GetListByContent',
    grpcWeb.MethodType.UNARY,
    share_pb.ShareContentIdRequest,
    share_pb.ShareList,
    (request: share_pb.ShareContentIdRequest) => {
      return request.serializeBinary();
    },
    share_pb.ShareList.deserializeBinary
  );

  getListByContent(
    request: share_pb.ShareContentIdRequest,
    metadata: grpcWeb.Metadata | null): Promise<share_pb.ShareList>;

  getListByContent(
    request: share_pb.ShareContentIdRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: share_pb.ShareList) => void): grpcWeb.ClientReadableStream<share_pb.ShareList>;

  getListByContent(
    request: share_pb.ShareContentIdRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: share_pb.ShareList) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/share.ShareService/GetListByContent',
        request,
        metadata || {},
        this.methodDescriptorGetListByContent,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/share.ShareService/GetListByContent',
    request,
    metadata || {},
    this.methodDescriptorGetListByContent);
  }

  methodDescriptorGetListByIdList = new grpcWeb.MethodDescriptor(
    '/share.ShareService/GetListByIdList',
    grpcWeb.MethodType.UNARY,
    share_pb.ShareIdListRequest,
    share_pb.ShareList,
    (request: share_pb.ShareIdListRequest) => {
      return request.serializeBinary();
    },
    share_pb.ShareList.deserializeBinary
  );

  getListByIdList(
    request: share_pb.ShareIdListRequest,
    metadata: grpcWeb.Metadata | null): Promise<share_pb.ShareList>;

  getListByIdList(
    request: share_pb.ShareIdListRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: share_pb.ShareList) => void): grpcWeb.ClientReadableStream<share_pb.ShareList>;

  getListByIdList(
    request: share_pb.ShareIdListRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: share_pb.ShareList) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/share.ShareService/GetListByIdList',
        request,
        metadata || {},
        this.methodDescriptorGetListByIdList,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/share.ShareService/GetListByIdList',
    request,
    metadata || {},
    this.methodDescriptorGetListByIdList);
  }

  methodDescriptorGetAll = new grpcWeb.MethodDescriptor(
    '/share.ShareService/GetAll',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    share_pb.ShareList,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    share_pb.ShareList.deserializeBinary
  );

  getAll(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null): Promise<share_pb.ShareList>;

  getAll(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: share_pb.ShareList) => void): grpcWeb.ClientReadableStream<share_pb.ShareList>;

  getAll(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: share_pb.ShareList) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/share.ShareService/GetAll',
        request,
        metadata || {},
        this.methodDescriptorGetAll,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/share.ShareService/GetAll',
    request,
    metadata || {},
    this.methodDescriptorGetAll);
  }

}

